name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to AWS
        uses: aws-actions/login@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build and push Docker image
        run: |
          docker build -t 008971660530.dkr.ecr.ap-southeast-2.amazonaws.com/v3s-assingment/v3s
          docker tag v3s-assingment/v3s:latest 008971660530.dkr.ecr.ap-southeast-2.amazonaws.com/v3s-assingment/v3s:latest
          docker push 008971660530.dkr.ecr.ap-southeast-2.amazonaws.com/v3s-assingment/v3s:latest
        

      - name: Deploy to ECS
        uses: aws-actions/deploy-ecs@v1
        with:
          cluster: ${{ secrets.ECS_CLUSTER }}
          task-definition: ${{ secrets.ECS_TASK_DEFINITION }}
          container-name: ${{ secrets.ECS_CONTAINER_NAME }}
          image: 008971660530.dkr.ecr.ap-southeast-2.amazonaws.com/v3s-assingment/v3s
      - name: Integration tests
        run: |
          # Your integration test commands here

      - name: Rollback
        uses: aws-actions/rollback-ecs@v1
        with:
          cluster: ${{ secrets.ECS_CLUSTER }}
          task-definition: ${{ secrets.ECS_TASK_DEFINITION }}
          container-name: ${{ secrets.ECS_CONTAINER_NAME }}
          image: 008971660530.dkr.ecr.ap-southeast-2.amazonaws.com/v3s-assingment/v3s
